#!/usr/bin/env python
import os

stream = os.popen('git status -uno --short')
output = stream.read()

if 'go.mod' in output:
  with open('go.mod', 'r') as f:
    for line in f:
      if 'replace' in line:
        print("Seu go.mod contem um replace pkg")
        exit(1)

    exit(0)