#!/bin/sh

ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/profile" "$HOME/.profile"
ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"

if [ ! -d "$HOME/.config/alacritty" ]; then mkdir $HOME/.config/alacritty; fi
ln -sf "$PWD/alacritty.yml" "$HOME/.config/alacritty/alacritty.yml"

if [ ! -d "$HOME/.config/nvim" ]; then mkdir $HOME/.config/nvim; fi
ln -sf "$PWD/init.vim" "$HOME/.config/nvim/init.vim"

ln -sf "$PWD/.git-prompt.sh" "$HOME/.git-prompt.sh"

if [ ! -d "$HOME/.config/gh" ]; then mkdir $HOME/.config/gh; fi
ln -sf "$PWD/gh/config.yml" "$HOME/.config/gh/config.yml"

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
