#!/bin/sh

# ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/.personal/gitconfig-personal" "$HOME/personal/.gitconfig"
ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/profile" "$HOME/.profile"
ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/zshrc" "$HOME/.zshrc"
ln -sf "$PWD/wezterm.lua" "$HOME/.wezterm.lua"

mkdir -p "$HOME/.config/alacritty" 
mkdir -p "$HOME/.config/gh" 

if [ ! -d "$HOME/.config/alacritty" ]; then mkdir $HOME/.config/alacritty; fi
ln -sf "$PWD/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"

ln -sf "$PWD/.git-prompt.sh" "$HOME/.git-prompt.sh"

if [ ! -d "$HOME/.config/gh" ]; then mkdir $HOME/.config/gh; fi
ln -sf "$PWD/gh/config.yml" "$HOME/.config/gh/config.yml"

ln -s "$PWD/nvim" "$HOME/.config"
