syntax on
set t_Co=256
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nowrap
set rnu
set number
set smartcase
set nobackup 
set noswapfile
set incsearch
set nohlsearch
set scrolloff=10
set spelllang=pt_br
set rtp+=~/.fzf
set updatetime=100
set visualbell
set paste
