#!/usr/bin/bash

dir=$(mktemp -d)
cd $dir
echo $(pwd)
curl -fLo fonts.zip https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.zip
unzip -x fonts.zip "*Complete Mono.ttf"
mv *.ttf ~/.local/share/fonts/

rm -rf $dir
